### GET all categories
GET http://localhost:8085/category/api/v1/list
X-API-Key: MULYONOSECRETSERVICE
Accept: application/json

### Create new category
POST http://localhost:8085/category/api/v1/add
X-API-Key: MULYONOSECRETSERVICE
Accept: application/json
Content-Type: application/json

{
  "name": "Barang Sembarangan"
}

### Get category by id
GET http://localhost:8085/category/api/v1/get/5
X-API-Key: MULYONOSECRETSERVICE
Accept: application/json

### Update category by id
PUT http://localhost:8085/category/api/v1/edit/1
X-API-Key: MULYONOSECRETSERVICE
Accept: application/json
Content-Type: application/json

{
  "name": "Barang Terlarang"
}

### Delete category by id
DELETE http://localhost:8085/category/api/v1/delete/2
X-API-Key: MULYONOSECRETSERVICE
Accept: application/json